service: data-validation
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DYNAMODB_TABLE: Heroes
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:ListStreams
            - dynamodb:DescribeStreams
            - dynamodb:Query
          Resource: arn:aws:dynamodb:us-east-1:*:table/Heroes

functions:
  hero-insert:
    handler: index.heroesInsert
    events:
      - http:
          path: heroes
          method: post
          cors: true
  hero-trigger:
    handler: index.heroesTrigger
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - HeroesTable
              - StreamArn

resources:
  Resources:
    HeroesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Heroes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
