version: '3.8'

services:
  localstack:
    container_name: 'localstack'
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  app:
    build: .
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - localstack
    environment:
      LOCALSTACK_HOST: localstack
volumes:
  nodemodules: {}
